---
- name: "Register all hosts and deploy /etc/hosts"
  hosts: all
  gather_facts: False
  tasks:

    - name: Populate service facts
      ansible.builtin.service_facts:

    - ansible.builtin.include_tasks: status.yml
      loop:
        - 'amq_streams_zookeeper.service'
        - 'amq_streams_broker.service'
      loop_control:
        loop_var: service_name

    - ansible.builtin.command: "ls /opt/"
      register: ls
      changed_when: False

    - ansible.builtin.debug:
        var: ls
